#imports random module
import random

#Explanation of Mastermind game
def explanation():
    print("==========================================================================")
    print("In Mastermind, you (the player) will be tasked to guess 4 correct colours")
    print("in a correct sequence which is generated by the computer. \n")
    print("You (the player) will only have 10 attempts for each game")
    print("and a list of available colours will be given. \n")
    print("After each attempt, you will be given a response on the number ")
    print("of colours you have guessed correct but are in the wrong position")
    print("and the number of colours you have guessed correct and are in")
    print("the correct position.")
    print("========================================================================== \n")
    
# checks if the answer is in the correct position
def AnsCheck(PlaAns,ComAns):

    #Accumulatior for element position index
    ElePos=0

    #Initial Number of correct colour and position
    CorPos=0

    #Empty list for Correct colour guess (CorCoGuess)
    CorCoGuess=[]

    #Copy of Computer Answer is created to prevent damage to the original 
    CopyComAns=ComAns.copy()
    
    #Checks if the element in Player's Answer(PlaAns) is in the Copy of Computer Answer(CopyComAns)
    for i in PlaAns:
        if i in CopyComAns :
            #Element is added to indicate that it is present in the Computers Answer
            CorCoGuess.append(i)

            #Element is removed to prevent the same element from being added again into CorCoGuess
            CopyComAns.remove(i)
            

    #checks if the element in PlaAns is in the same position as ComAns     
    while ElePos<4:
        if PlaAns[ElePos]==ComAns[ElePos]:
            ElePos+=1

            #if element in PlaAns is in same position as ComAns, CorPos increases by 1
            CorPos+=1

        else:
            ElePos+=1

    #the total number correct colour guess deducted with the total number of correct colours in the correct position
    #to obtain the number of correct colour but in wrong position.
    NewCorCoGuess=len(CorCoGuess)- CorPos

    return CorPos,NewCorCoGuess


# prints a welcome message and instructions for the player
def welcome():
    print("Hello and welcome to a game of Mastermind. \n")
    print("Do you know how to play Mastermind?")

    #ask the player if the player needs an explanation for Mastermind
    Question=input("Press [y] for an explanation or press any other key to continue to the game \n")
    if Question.lower()== 'y':
        explanation()
    print("Lets start the game. \n")
    print("Only type the first letter of the colour when guessing")
    print("and don't put spaces in between your guesses. \n")
    print("Here is an example of a guess, =>   rpbg  \n")
    print("Here is the list of available colours, Good luck!")
    print("Red(r), Blue(b) ,Yellow(y) ,Green(g), Purple(p), White(w) \n")    

# checks if the length of input list is 4,
# then checks if the player inputs 4 of the proper colours given
def listNumCheck(PlaAns,CoList,ComAns):
    
    #prints error message if Player input length is less than 4
    if len(PlaAns)<4:
        print("Please Complete your answer")
        return "e",0

    #prints error message if Player input length is more than 4    
    elif len(PlaAns)>4:
        print("Do not type in more than 4 inputs")
        return "e",0

    #Code is executed if Player input length is 4
    elif len(PlaAns)==4:

        #Empty list for Player Answer Correct Colour (PACorCO)
        PACorCo=[]

        #checks if element in Player's Answer (PlaAns) is in the list of colours(CoList)
        for x in PlaAns:            
            if x in CoList:

                #Adds element into PACorCo list if element is present in the list of colours
                PACorCo.append(x)

        #prints error message if inital input length is 4 but does not contain the colours given by computer
        if len(PACorCo)<4:
            print("Please type in the proper colours given")
            return "e",0

        #Code is executed when 4 alphabet of colours from colour list is present
        elif len(PACorCo)==4:
            
            #Goes through function AnsCheck for answers
            CorPos,NewCorCoGuess=AnsCheck(PlaAns,ComAns)
            
            return CorPos,NewCorCoGuess    

# the main program of the game 
def main():
    welcome()
    
    #The list of the colours first alphabet 
    CoList=["r","b","y","g","p","w"]

    #Generates a random 4 colour code using the elements in Colist
    ComAns=random.choices(CoList,k=4)

    #Inital number of attempts when starting a game and Attempt Accumulator
    Attempt=0
    
    while Attempt<10:
        #Increases Attempt by 1 for each loop
        Attempt+=1

        #Shows current number of attempts
        print("Attempt number:",Attempt)
    
        #Prompts the Player to answer
        playerset=input("Please input your 4 colours : ")

        #Removes white space in Player's Answer
        playerset2=playerset.replace(" ","")
        
        #Changes Player's Answer to lowercase
        PlaAns=playerset2.lower()
        
        #Goes through function listNumCheck for results
        CorPos,NewCorCoGuess=listNumCheck(PlaAns,CoList,ComAns)

        #Prints blank line if input error detected
        if CorPos=="e":
            print("")

        #Shows the results of the players guess
        elif CorPos<4:
            print("You have guessed ",NewCorCoGuess," correct colour but in wrong position.")
            print("You have guessed ",CorPos," correct colour in right position.")
            print(" ")


        #Stops the loop and prints Congratulation message when player guess all correct
        elif CorPos==4:
            print("")
            print("Congratulations!, you managed to guess all 4 of the")
            print("correct colous in the correct position! \n")
            print("Your total number of attempts is",Attempt,".")
            break


        #Prints game over message after the 10th attempt and the player did not guess the right answer
        if Attempt==10 and CorPos!=4:
            print("Game Over, better luck next time.")
            print("The Answer was",ComAns)
            
main()


